/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OmOssIndexRouteImport } from './routes/om-oss/index'
import { Route as KalenderIndexRouteImport } from './routes/kalender/index'
import { Route as FChar246reningenIndexRouteImport } from './routes/föreningen/index'
import { Route as EvenemangIndexRouteImport } from './routes/evenemang/index'
import { Route as RiddareKnightIdRouteImport } from './routes/riddare/$knightId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssIndexRoute = OmOssIndexRouteImport.update({
  id: '/om-oss/',
  path: '/om-oss/',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderIndexRoute = KalenderIndexRouteImport.update({
  id: '/kalender/',
  path: '/kalender/',
  getParentRoute: () => rootRouteImport,
} as any)
const FChar246reningenIndexRoute = FChar246reningenIndexRouteImport.update({
  id: '/föreningen/',
  path: '/föreningen/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenemangIndexRoute = EvenemangIndexRouteImport.update({
  id: '/evenemang/',
  path: '/evenemang/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiddareKnightIdRoute = RiddareKnightIdRouteImport.update({
  id: '/riddare/$knightId',
  path: '/riddare/$knightId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/riddare/$knightId': typeof RiddareKnightIdRoute
  '/evenemang/': typeof EvenemangIndexRoute
  '/föreningen/': typeof FChar246reningenIndexRoute
  '/kalender/': typeof KalenderIndexRoute
  '/om-oss/': typeof OmOssIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/riddare/$knightId': typeof RiddareKnightIdRoute
  '/evenemang': typeof EvenemangIndexRoute
  '/föreningen': typeof FChar246reningenIndexRoute
  '/kalender': typeof KalenderIndexRoute
  '/om-oss': typeof OmOssIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/riddare/$knightId': typeof RiddareKnightIdRoute
  '/evenemang/': typeof EvenemangIndexRoute
  '/föreningen/': typeof FChar246reningenIndexRoute
  '/kalender/': typeof KalenderIndexRoute
  '/om-oss/': typeof OmOssIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/riddare/$knightId'
    | '/evenemang/'
    | '/föreningen/'
    | '/kalender/'
    | '/om-oss/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/riddare/$knightId'
    | '/evenemang'
    | '/föreningen'
    | '/kalender'
    | '/om-oss'
  id:
    | '__root__'
    | '/'
    | '/riddare/$knightId'
    | '/evenemang/'
    | '/föreningen/'
    | '/kalender/'
    | '/om-oss/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RiddareKnightIdRoute: typeof RiddareKnightIdRoute
  EvenemangIndexRoute: typeof EvenemangIndexRoute
  FChar246reningenIndexRoute: typeof FChar246reningenIndexRoute
  KalenderIndexRoute: typeof KalenderIndexRoute
  OmOssIndexRoute: typeof OmOssIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss/': {
      id: '/om-oss/'
      path: '/om-oss'
      fullPath: '/om-oss/'
      preLoaderRoute: typeof OmOssIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender/': {
      id: '/kalender/'
      path: '/kalender'
      fullPath: '/kalender/'
      preLoaderRoute: typeof KalenderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/föreningen/': {
      id: '/föreningen/'
      path: '/föreningen'
      fullPath: '/föreningen/'
      preLoaderRoute: typeof FChar246reningenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenemang/': {
      id: '/evenemang/'
      path: '/evenemang'
      fullPath: '/evenemang/'
      preLoaderRoute: typeof EvenemangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riddare/$knightId': {
      id: '/riddare/$knightId'
      path: '/riddare/$knightId'
      fullPath: '/riddare/$knightId'
      preLoaderRoute: typeof RiddareKnightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RiddareKnightIdRoute: RiddareKnightIdRoute,
  EvenemangIndexRoute: EvenemangIndexRoute,
  FChar246reningenIndexRoute: FChar246reningenIndexRoute,
  KalenderIndexRoute: KalenderIndexRoute,
  OmOssIndexRoute: OmOssIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
